import Link from 'next/link'

export default function CopyrightNoticePage() {
  return (
    <main className="wrap" style={{ padding: '80px 0' }}>
      <p className="kicker">Legal</p>
      <h1>Copyright Notice</h1>
      <p className="lead" style={{ maxWidth: 820 }}>
        &copy; 2026 MCF.DIGITAL Intelligence. All rights reserved.
      </p>

      <div className="sp-24" />

      <section style={{ padding: 0, borderBottom: 'none' }} className="grid">
        <article className="card">
          <h2>Ownership</h2>
          <p>
            All content on the MCF.DIGITAL Intelligence Platform, including but not limited to text,
            graphics, calculator logic, mathematical methodologies, educational materials, user
            interface designs, source code, and documentation, is the property of MCF.DIGITAL and is
            protected under United States and international copyright laws.
          </p>
        </article>

        <article className="card">
          <h2>Permitted Use</h2>
          <ul style={{ margin: 0, paddingLeft: 20, display: 'grid', gap: 10 }}>
            <li>
              You may use the Platform and its calculators for personal, non-commercial evaluation of
              gas monetization projects.
            </li>
            <li>
              You may print or save calculator reports generated by the Platform for your own
              records.
            </li>
            <li>
              You may reference methodology documentation for educational purposes, provided proper
              attribution is given.
            </li>
          </ul>
        </article>

        <article className="card">
          <h2>Prohibited Use</h2>
          <ul style={{ margin: 0, paddingLeft: 20, display: 'grid', gap: 10 }}>
            <li>
              Reproducing, distributing, or publicly displaying Platform content without written
              permission.
            </li>
            <li>Creating derivative works based on Platform calculator logic or methodology.</li>
            <li>Using Platform content in competing products or services.</li>
            <li>Removing or altering copyright notices, watermarks, or attribution.</li>
            <li>Scraping, crawling, or automated extraction of Platform content.</li>
          </ul>
        </article>

        <article className="card">
          <h2>Trademarks</h2>
          <p>
            &quot;MCF.DIGITAL,&quot; the MCF.DIGITAL logo, and &quot;Intelligence Platform&quot; are
            trademarks of MCF.DIGITAL. All other product and company names mentioned may be
            trademarks of their respective owners.
          </p>
        </article>

        <article className="card">
          <h2>Third-Party Content</h2>
          <p>
            Market data displayed on the Platform (Bitcoin prices, network difficulty, Henry Hub
            pricing) is sourced from publicly available third-party APIs and remains the property of
            its respective providers. Mathematical formulas used in calculators are based on publicly
            documented petroleum engineering and financial mathematics standards.
          </p>
        </article>

        <article className="card">
          <h2>DMCA &amp; Infringement Claims</h2>
          <p>
            If you believe any content on the Platform infringes your copyright, please contact us
            via our <Link href="/contact">contact page</Link> with:
          </p>
          <ul style={{ margin: 0, paddingLeft: 20, display: 'grid', gap: 10 }}>
            <li>Identification of the copyrighted work.</li>
            <li>
              Identification of the infringing material and its location on the Platform.
            </li>
            <li>Your contact information and a statement of good faith belief.</li>
            <li>Your physical or electronic signature.</li>
          </ul>
        </article>

        <article className="card">
          <h2>Licensing Inquiries</h2>
          <p>
            For commercial licensing, white-label partnerships, or permission to use Platform content
            beyond the scope of permitted use, please <Link href="/contact">contact us</Link>.
          </p>
        </article>
      </section>
    </main>
  )
}
